// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Migrator;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Migrator.Migrations
{
    [DbContext(typeof(MigrationDbContext))]
    [Migration("20261003213318_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Migrator.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric")
                        .HasColumnName("rate");

                    b.HasKey("Id")
                        .HasName("pk_currency");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_currency_name");

                    b.ToTable("currency", (string)null);
                });

            modelBuilder.Entity("Migrator.Entities.RevokedToken", b =>
                {
                    b.Property<string>("Jti")
                        .HasColumnType("text")
                        .HasColumnName("jti");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.HasKey("Jti")
                        .HasName("pk_revoked_token");

                    b.ToTable("revoked_token", (string)null);
                });

            modelBuilder.Entity("Migrator.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_user_name");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Migrator.Entities.UserFavoriteCurrency", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer")
                        .HasColumnName("currency_id");

                    b.HasKey("UserId", "CurrencyId")
                        .HasName("pk_user_favorite_currency");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_user_favorite_currency_currency_id");

                    b.ToTable("user_favorite_currency", (string)null);
                });

            modelBuilder.Entity("Migrator.Entities.UserFavoriteCurrency", b =>
                {
                    b.HasOne("Migrator.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_favorite_currency_currency_currency_id");

                    b.HasOne("Migrator.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_favorite_currency_user_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
